### ISSUE TITLE
✨ [FEAT] Mybatis 설정, Member Domain, Dao, Mapper 구현

### ISSUE THREAD

**Issue by NamYeonW00** [ForYourNutrition/ForYourNutrition_ex#6]
### Description

> description
- Mybatis 설정, Member Domain, Dao, Mapper 구현

### Todo
- [x] Mybatis 설정
- [x] Member Domain 구현
- [x] Member Dao 구현
- [x] Member Mapper 구현

#ETC
-
